import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";


export const metadata: Metadata = {
  title: "Assignment-1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-amber-400">
        <Navbar />
        {children}
      </body>
    </html>
  );
}